In [7]:
def print_matrix(matrix, step=None):
    """打印矩阵，带有可选的步骤说明"""
    if step:
        print(f"\n步骤 {step}:")
    for row in matrix:
        print("[", end=" ")
        for num in row:
            print(f"{num:1}", end=" ")
        print("]")
    print()

def find_pivot_row(matrix, col, row):
    """找到主元行（当前列中绝对值最大的元素所在的行）"""
    max_row = row
    max_val = abs(matrix[row][col])
    
    for i in range(row, len(matrix)):
        if abs(matrix[i][col]) > max_val:
            max_val = abs(matrix[i][col])
            max_row = i
    return max_row

In [ ]:
def print_matrix(matrix, step=None):
    """打印矩阵，带有可选的步骤说明"""
    if step:
        print(f"\n步骤 {step}:")
    for row in matrix:
        print("[", end=" ")
        for num in row:
            # 格式化输出，保持整洁
            print(f"{num:4}", end=" ")
        print("]")
    print()

def find_pivot_row(matrix, col, row):
    """找到主元行（当前列中绝对值最大的元素所在的行）"""
    max_row = row
    max_val = abs(matrix[row][col])
    
    for i in range(row, len(matrix)):
        if abs(matrix[i][col]) > max_val:
            max_val = abs(matrix[i][col])
            max_row = i
    return max_row

def gaussian_elimination(matrix):
    """
    高斯消元法求解线性方程组
    输入: 增广矩阵 (每行最后一个元素是常数项)
    输出: 行最简形矩阵和每一步的说明
    """
    # 将矩阵转换为浮点数以避免整数除法问题
    matrix = [list(map(float, row)) for row in matrix]
    
    n_rows = len(matrix)
    n_cols = len(matrix[0])
    step = 1
    
    print("初始矩阵:")
    print_matrix(matrix)
    
    for col in range(n_cols - 1):  # 最后一列是常数项，不需要处理
        # 找到主元行
        pivot_row = find_pivot_row(matrix, col, col)
        
        # 如果主元行不是当前行，则交换行
        if pivot_row != col:
            matrix[col], matrix[pivot_row] = matrix[pivot_row], matrix[col]
            print_matrix(matrix, f"{step}: 交换行 {col+1} 和行 {pivot_row+1} 以获取主元")
            step += 1
        
        # 如果主元接近0，则无法继续消元（矩阵奇异）
        if abs(matrix[col][col]) < 1e-10:
            print("矩阵是奇异的，没有唯一解")
            return matrix
        
        # 将主元行标准化，使主元为1（使用浮点数除法）
        pivot = matrix[col][col]
        if not abs(pivot - 1.0) < 1e-10:  # 如果主元不是1
            for j in range(col, n_cols):
                matrix[col][j] /= pivot  # 使用浮点数除法
            print_matrix(matrix, f"{step}: 将行 {col+1} 除以 {pivot:.4f} 使主元为1")
            step += 1
        
        # 消去下方和上方的元素
        for i in range(n_rows):
            if i != col and not abs(matrix[i][col]) < 1e-10:
                factor = matrix[i][col]
                for j in range(col, n_cols):
                    matrix[i][j] -= factor * matrix[col][j]
                print_matrix(matrix, f"{step}: 行 {i+1} 减去 {factor:.4f} 倍行 {col+1} 以消去第 {col+1} 列元素")
                step += 1
    
    print("行最简形矩阵:")
    print_matrix(matrix)
    
    # 提取解
    solution = [row[-1] for row in matrix]
    print("解为:")
    for i, val in enumerate(solution):
        print(f"x{i+1} = {val:.4f}")
    
    return matrix



In [9]:
def matrix_multiply(A, B):
    """计算两个矩阵的乘积"""
    # 获取矩阵维度
    m = len(A)          # A的行数
    n = len(B)          # B的行数，应等于A的列数
    p = len(B[0])       # B的列数
    
    # 检查矩阵是否可乘
    if len(A[0]) != n:
        raise ValueError("第一个矩阵的列数必须等于第二个矩阵的行数")
    
    # 初始化结果矩阵
    result = [[0 for _ in range(p)] for _ in range(m)]
    
    # 计算乘积
    print("计算过程：")
    for i in range(m):
        for j in range(p):
            # 计算result[i][j] = A的第i行与B的第j列对应元素乘积之和
            total = 0
            calculation = []
            for k in range(n):
                product = A[i][k] * B[k][j]
                total += product
                calculation.append(f"{A[i][k]}×{B[k][j]}")
            result[i][j] = total
            print(f"result[{i}][{j}] = {' + '.join(calculation)} = {total}")
    
    return result

In [10]:
# 定义3×2矩阵A
A = [
    [2, 3],
    [4, 1],
    [5, 2]
]

# 定义2×4矩阵B
B = [
    [3, 1, 4, 2],
    [2, 5, 3, 1]
]

# 打印原始矩阵
print_matrix(A, "3×2矩阵A")
print_matrix(B, "2×4矩阵B")

# 计算并打印结果
result = matrix_multiply(A, B)
print()
print_matrix(result, "结果矩阵(3×4)")


步骤 3×2矩阵A:
[ 2 3 ]
[ 4 1 ]
[ 5 2 ]


步骤 2×4矩阵B:
[ 3 1 4 2 ]
[ 2 5 3 1 ]

计算过程：
result[0][0] = 2×3 + 3×2 = 12
result[0][1] = 2×1 + 3×5 = 17
result[0][2] = 2×4 + 3×3 = 17
result[0][3] = 2×2 + 3×1 = 7
result[1][0] = 4×3 + 1×2 = 14
result[1][1] = 4×1 + 1×5 = 9
result[1][2] = 4×4 + 1×3 = 19
result[1][3] = 4×2 + 1×1 = 9
result[2][0] = 5×3 + 2×2 = 19
result[2][1] = 5×1 + 2×5 = 15
result[2][2] = 5×4 + 2×3 = 26
result[2][3] = 5×2 + 2×1 = 12


步骤 结果矩阵(3×4):
[ 12 17 17 7 ]
[ 14 9 19 9 ]
[ 19 15 26 12 ]



In [29]:
import numpy as np

A1 = np.array([[2, 1, 0, 3], [1, -1, 1, 4], [2, 1, -1, -1]])
P1 = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
A2 = np.dot(P1, A1)

print(f'A1: \n{A1}\n') 
print(f'P1: \n{P1}\n')
print(f'A2=P1*A1: \n{A2}\n')  # P1 @ A1

P2 = np.array([[1, 0, 0], [-2, 1, 0], [-2, 0, 1]])
A3 = np.dot(P2, A2)

print(f'P2: \n{P2}\n')
print(f'A3=P2*P1*A1: \n{A3}\n')  # P1 @ A1

P3 = np.array([[1, 0, 0], [0, 1, 0], [0, -1, 1]])
A4 = np.dot(P3, A3)

print(f'P3: \n{P3}\n')
print(f'A4=P3*P2*P1*A1: \n{A4}\n')  # P1 @ A

P4 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, -1]])
A5 = np.dot(P4, A4)

P3P = np.dot(P4, P3)

print(f'P4: \n{P4}\n')
print(f'P3P=P4*P3:\n{P3P}\n')
print(f'A4=P3*P2*P1*A1: \n{A4}\n')  # P3 @ P2 @ P1 @ A1
print(f'A5=P4*P3*P2*P1*A1: \n{A5}\n')  # P4 @ P3 @P2 @P1 @ A1

# Inverse
# 计算各变换矩阵的逆矩阵（初等矩阵的逆矩阵）
P4_inv = np.array([[1, 0, 0], [0, 1, 0], [0, 0, -1]])  # P4是行缩放，逆矩阵同P4（缩放系数倒数）
P3_inv = np.array([[1, 0, 0], [0, 1, 0], [0, 1, 1]])   # P3是行3=行3-1*行2，逆为行3=行3+1*行2
P2_inv = np.array([[1, 0, 0], [2, 1, 0], [2, 0, 1]])   # P2是行2=行2-2*行1，逆为行2=行2+2*行1；行3同理
P1_inv = P1                                           # P1是行交换，逆矩阵是自身

P3P_inv = np.dot(P3_inv, P4_inv)

# 第一步：A5左乘P4_inv → 得到A4
A4_rev = np.dot(P4_inv, A5)
# 第二步：A4_rev左乘P3_inv → 得到A3
A3_rev = np.dot(P3_inv, A4_rev)
# 第三步：A3_rev左乘P2_inv → 得到A2
A2_rev = np.dot(P2_inv, A3_rev)
# 第四步：A2_rev左乘P1_inv → 得到A1
A1_rev = np.dot(P1_inv, A2_rev)


# 打印逆变换矩阵及中间结果
print("=== 逆变换矩阵 ===")
print(f'P3P_inv:\n{P3P_inv}\n')
print(f'P4的逆矩阵 P4_inv:\n{P4_inv}\n')
print(f'P3的逆矩阵 P3_inv:\n{P3_inv}\n')
print(f'P2的逆矩阵 P2_inv:\n{P2_inv}\n')
print(f'P1的逆矩阵 P1_inv:\n{P1_inv}\n')

print("=== 逆变换过程（A5 → A1） ===")
print(f'A5:\n{A5}\n')
print(f'A4_rev = P4_inv * A5:\n{A4_rev}\n')  # 对应原始A4
print(f'A3_rev = P3_inv * A4_rev:\n{A3_rev}\n')  # 对应原始A3
print(f'A2_rev = P2_inv * A3_rev:\n{A2_rev}\n')  # 对应原始A2
print(f'A1_rev = P1_inv * A2_rev:\n{A1_rev}\n')  # 恢复为原始A1

# 验证是否与原始A1一致
print("验证是否恢复原始A1：", np.allclose(A1_rev, A1))  # 输出 True 表示一致

A1: 
[[ 2  1  0  3]
 [ 1 -1  1  4]
 [ 2  1 -1 -1]]

P1: 
[[0 1 0]
 [1 0 0]
 [0 0 1]]

A2=P1*A1: 
[[ 1 -1  1  4]
 [ 2  1  0  3]
 [ 2  1 -1 -1]]

P2: 
[[ 1  0  0]
 [-2  1  0]
 [-2  0  1]]

A3=P2*P1*A1: 
[[ 1 -1  1  4]
 [ 0  3 -2 -5]
 [ 0  3 -3 -9]]

P3: 
[[ 1  0  0]
 [ 0  1  0]
 [ 0 -1  1]]

A4=P3*P2*P1*A1: 
[[ 1 -1  1  4]
 [ 0  3 -2 -5]
 [ 0  0 -1 -4]]

P4: 
[[ 1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]

P3P=P4*P3:
[[ 1  0  0]
 [ 0  1  0]
 [ 0  1 -1]]

A4=P3*P2*P1*A1: 
[[ 1 -1  1  4]
 [ 0  3 -2 -5]
 [ 0  0 -1 -4]]

A5=P4*P3*P2*P1*A1: 
[[ 1 -1  1  4]
 [ 0  3 -2 -5]
 [ 0  0  1  4]]

=== 逆变换矩阵 ===
P3P_inv:
[[ 1  0  0]
 [ 0  1  0]
 [ 0  1 -1]]

P4的逆矩阵 P4_inv:
[[ 1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]

P3的逆矩阵 P3_inv:
[[1 0 0]
 [0 1 0]
 [0 1 1]]

P2的逆矩阵 P2_inv:
[[1 0 0]
 [2 1 0]
 [2 0 1]]

P1的逆矩阵 P1_inv:
[[0 1 0]
 [1 0 0]
 [0 0 1]]

=== 逆变换过程（A5 → A1） ===
A5:
[[ 1 -1  1  4]
 [ 0  3 -2 -5]
 [ 0  0  1  4]]

A4_rev = P4_inv * A5:
[[ 1 -1  1  4]
 [ 0  3 -2 -5]
 [ 0  0 -1 -4]]

A3_rev = P3_inv * A4_rev:
[[ 1 -1